version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=project

  web:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    command: php /home/docker/html/artisan serve --host=0.0.0.0
    ports:
      - 127.0.0.1:8001:8000
    links:
      - db
    volumes:
      - .:/home/docker/html/
