version: '2'

services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=project
    ports:
      - 3308:3306

  web:
    build: .
    command: php /home/docker/html/artisan serve --host=0.0.0.0
    ports:
      - 8000:8000
    links:
      - db
    volumes:
      - .:/home/docker/html/
